import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Poppins } from 'next/font/google';
import { ModalProvider } from "./context/ModalContext";

import { Anton, Plus_Jakarta_Sans  } from 'next/font/google';
import BeeCursor from "./curser/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
    weights: ['400', '500', '600', '700', '800'],

});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-poppins',
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const anton = Anton({
  subsets: ['latin'],
  weight: '400', // Anton only has 400
});
export const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weights: ['400', '500', '600', '700', '800'],
  variable: '--font-plus-jakarta',
});
export const metadata = {
  title: "Beeyoond Gaming",
  description: "Generated by create next app",
   icons: {
    icon: '/images/favicon.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
      <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} 
       ${poppins.variable}  ${anton.variable}  ${plusJakarta.variable} `}>
        <ModalProvider>
        {children}
        </ModalProvider>
        <ToastContainer 
        position="top-center" 
        autoClose={3000} 
        hideProgressBar={false} 
        newestOnTop={false} 
        closeOnClick 
        rtl={false} 
        pauseOnFocusLoss 
        draggable 
        pauseOnHover 
        theme="light"
      />
        {/* <BeeCursor /> */}
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        
      </body>
    </html>
  );
}
